package com.enoluca.ytd.data.model

enum class FormatKind { VIDEO, AUDIO }

enum class QualityTier { LOW, MEDIUM, HIGH, BEST }

/** A numeric field that may be genuinely unknown or an estimate rather than an exact value. */
sealed interface Metric<out T> {
    data class Known<T>(val value: T) : Metric<T>
    data class Estimated<T>(val value: T) : Metric<T>
    data object Unknown : Metric<Nothing>
}

fun <T> Metric<T>?.orUnknown(): Metric<T> = this ?: Metric.Unknown

/**
 * A single downloadable stream as reported by the provider (yt-dlp), never fabricated.
 * Video and audio-only streams are both represented here; [kind] distinguishes them.
 */
data class MediaFormat(
    val formatId: String,
    val kind: FormatKind,
    val container: String?,
    val resolutionLabel: String?,
    val heightPx: Int?,
    val fps: Int?,
    val videoCodec: String?,
    val audioCodec: String?,
    val hasAudio: Boolean,
    val isHdr: Boolean,
    val bitrateKbps: Metric<Int>,
    val sampleRateHz: Metric<Int>,
    val fileSizeBytes: Metric<Long>,
    val tier: QualityTier,
    /**
     * For audio: the fixed MP3 bitrate ffmpeg encodes to. Null means "Original quality (VBR)":
     * the encoder picks the bitrate per frame. Null must never be replaced by a default bitrate.
     */
    val mp3BitrateKbps: Int? = null,
    /** Audio kept exactly as the source provides it (e.g. M4A) — no MP3 re-encode. */
    val nativeAudio: Boolean = false,
    /** "Best available" pseudo-option: yt-dlp picks the best video+audio at download time. */
    val isBestAvailable: Boolean = false,
    /** Only ever set from what the extractor reports; see [Watermark]. */
    val watermark: Watermark = Watermark.UNKNOWN,
) {
    val isVbrAudio: Boolean
        get() = kind == FormatKind.AUDIO && !nativeAudio && mp3BitrateKbps == null

    /** Unique per list row — the MP3 options all share the same source [formatId]. */
    val key: String
        get() = when {
            isBestAvailable -> "best"
            kind == FormatKind.VIDEO -> formatId
            nativeAudio -> "$formatId@native"
            mp3BitrateKbps == null -> "$formatId@vbr"
            else -> "$formatId@$mp3BitrateKbps"
        }

    val displayLabel: String
        get() = when (kind) {
            FormatKind.VIDEO -> when {
                isBestAvailable -> "Best available"
                else -> resolutionLabel ?: heightPx?.let { "${it}p" } ?: "Unknown resolution"
            }
            FormatKind.AUDIO -> when {
                nativeAudio -> "${container?.uppercase() ?: "Audio"} · Original"
                mp3BitrateKbps != null -> "MP3 · $mp3BitrateKbps kbps"
                else -> "MP3 · Original quality (VBR)"
            }
        }

    /** Common name for standard video resolutions ("HD", "Full HD", …); null for non-standard ones. */
    val qualityName: String?
        get() = if (kind != FormatKind.VIDEO) null else if (isBestAvailable) heightPx?.let { "up to ${it}p" } else when (heightPx) {
            4320 -> "8K"
            2160 -> "4K Ultra HD"
            1440 -> "2K"
            1080 -> "Full HD"
            720 -> "HD"
            else -> null
        }
}

/**
 * Watermark information as reported by the extractor. We never claim to *remove* a watermark:
 * WATERMARKED / NO_WATERMARK are only set when the extractor itself distinguishes streams
 * (e.g. TikTok's format notes), and UNKNOWN otherwise.
 */
enum class Watermark { UNKNOWN, WATERMARKED, NO_WATERMARK }

data class SubtitleTrack(
    val languageCode: String,
    val languageName: String,
    val isAutoGenerated: Boolean,
)

/** Real metadata retrieved for a detected URL. Never invented — missing fields stay null. */
data class MediaInfo(
    val sourceUrl: String,
    val webpageUrl: String,
    val title: String,
    val uploader: String?,
    val thumbnailUrl: String?,
    val durationSeconds: Long?,
    val videoFormats: List<MediaFormat>,
    val audioFormats: List<MediaFormat>,
    val subtitles: List<SubtitleTrack>,
    val extractorKey: String?,
)
